version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/app

    command: ionic serve --host 0.0.0.0 --port 8100 --disableHostCheckl
    environment:
      - NODE_ENV=development
