version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    command: /bin/sh -c "npm install && ionic serve --host 0.0.0.0 --port 8100 --disableHostCheck"
    environment:
      - NODE_ENV=development